# Generated by Django 5.2.3 on 2025-06-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='concluded',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='item1_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='item1_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='item2_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='item2_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='item3_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 3'),
        ),
        migrations.AddField(
            model_name='task',
            name='item3_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 3'),
        ),
        migrations.AddField(
            model_name='task',
            name='item4_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 4'),
        ),
        migrations.AddField(
            model_name='task',
            name='item4_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 4'),
        ),
        migrations.AddField(
            model_name='task',
            name='item5_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 5'),
        ),
        migrations.AddField(
            model_name='task',
            name='item5_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 5'),
        ),
        migrations.AddField(
            model_name='task',
            name='item6_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 6'),
        ),
        migrations.AddField(
            model_name='task',
            name='item6_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 6'),
        ),
        migrations.AddField(
            model_name='task',
            name='item7_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 7'),
        ),
        migrations.AddField(
            model_name='task',
            name='item7_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 7'),
        ),
        migrations.AddField(
            model_name='task',
            name='item8_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 8'),
        ),
        migrations.AddField(
            model_name='task',
            name='item8_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 8'),
        ),
        migrations.AddField(
            model_name='task',
            name='item9_done',
            field=models.BooleanField(default=False, verbose_name='Concluído 9'),
        ),
        migrations.AddField(
            model_name='task',
            name='item9_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Item 9'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Pessoais', max_length=100, verbose_name='Nome da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade da Categoria'),
        ),
    ]
