# Generated by Django 5.2.3 on 2025-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_note_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='border_color',
            field=models.CharField(choices=[('border-danger', 'Vermelho'), ('border-primary', 'Azul'), ('border-success', 'Verde'), ('border-info', 'Azul Claro'), ('border-warning', 'Amarelo'), ('border-secondary', 'Cinza')], default='border-primary', max_length=20, verbose_name='Cor da Borda'),
        ),
    ]
