# Generated by Django 5.2.3 on 2025-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_remove_task_item1_done_remove_task_item2_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Agenda/fotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item1_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item2_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item3_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item4_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item5_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item6_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 6'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item7_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 7'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item8_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 8'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item9_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Item 9'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Nome da Categoria'),
        ),
    ]
