# Generated by Django 5.2.3 on 2025-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0007_date_delete_importantedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
