# Generated by Django 5.2.3 on 2025-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0008_alter_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Data Fixa (Não Excluível)'),
        ),
    ]
