# Generated by Django 5.2.3 on 2025-06-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportanteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Data Importante',
                'verbose_name_plural': 'Datas Importantes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tópico')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('border_color', models.CharField(choices=[('border-danger', 'Vermelho'), ('border-primary', 'Azul'), ('border-success', 'Verde'), ('border-info', 'Azul Claro'), ('border-warning', 'Amarelo'), ('border-secondary', 'Cinza')], default='border-primary', max_length=20, verbose_name='Cor da Borda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto da Frase')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Frase do Dia',
                'verbose_name_plural': 'Frases do Dia',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('type', models.CharField(default='Pessoais', max_length=50, verbose_name='Tipo de Tarefa')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('concluded', models.BooleanField(default=False, verbose_name='Concluída')),
            ],
        ),
    ]
