# Generated by Django 5.2.3 on 2025-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_remove_task_concluded_remove_task_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='item1_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item2_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item3_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item4_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item5_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item6_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item7_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item8_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='item9_done',
        ),
        migrations.AlterField(
            model_name='task',
            name='item1_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item2_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item3_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item4_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item5_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item6_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 6'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item7_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 7'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item8_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 8'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item9_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item 9'),
        ),
    ]
