# Generated by Django 5.2.3 on 2025-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_note_foto_alter_task_item1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade da Categoria'),
        ),
    ]
