# Generated by Django 5.2.3 on 2025-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_alter_task_name_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Agenda/fotos/'),
        ),
    ]
